/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:c0241052-27e1-46e7-a2f9-4b1e5f100642",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_IJSAK0lBl",
    "aws_user_pools_web_client_id": "646j0mmriprfb4mo4mfn4tpekc",
    "oauth": {}
};


export default awsmobile;
